In [146]:
#Importing the Nominatim geocoder class 
from geopy.geocoders import Nominatim
import pandas as pd
from geopy.extra.rate_limiter import RateLimiter
import urllib
import requests
from geopy.geocoders import GoogleV3
from geopy import distance
from numpy import radians, cos, sin, sqrt
from numpy import arcsin as asin


import csv
import pandas as pd
import googlemaps

from geopy.geocoders import GoogleV3

import pandas as pd
import numpy as np
import pandas_gbq
import pygsheets
from google.oauth2.service_account import Credentials
from oauth2client.service_account import ServiceAccountCredentials
from tqdm import tqdm
import time
import datetime as dt
# Multi-processing
from multiprocessing import Pool, cpu_count
import warnings
warnings.filterwarnings("ignore")

In [147]:
credentials = Credentials.from_service_account_file('C:/Users/leemn/Documents/Loop Service Account/cb-prod-297913-623cea238b9a.json')

In [157]:
query_orders = '''
SELECT trip_id, trip_client_id, driver.name AS driver_name, order_id, order_no,
branch.name AS branch_name, branch.address AS branch_address, 
branch.location.latitude AS branch_lat,
branch.location.longitude AS branch_lon,
customer.name AS customer_name,
customer_location.latitude AS customer_lat,
customer_location.longitude AS customer_lon,
delivery_distance,
created_at,
CASE
WHEN trip_client_id = "zRpxC1kyh7ge4VlC0iu3" THEN "Ackermans Pharmacy"
WHEN trip_client_id = "hy7Y3kxHgg0Q4KMSMyma" THEN "Aletts Rusks"
WHEN trip_client_id = "r5Hb7LUqu0kk2Qd3AbB7" THEN "Andiccio24"
WHEN trip_client_id = "yCVhIFW0V2WLbjTmY5tB" THEN "Aramex"
WHEN trip_client_id = "NBinKwRfPr4vVbqZrupA" THEN "Belgotex"
WHEN trip_client_id = "NsPHG9HCJw5Tgw4bVkUh" 
OR  trip_client_id = "OMRNyS6UcsFNObl2xcwe" THEN "Busymed"
--WHEN trip_client_id = "OMRNyS6UcsFNObl2xcwe" THEN "Cornerstone Pharmacy"
WHEN trip_client_id = "CGTBlA89wEzDe3xyWjPy" THEN "Busymed Sandbox"
WHEN trip_client_id = "tJxbNK75n4YJ6Oumro0k" THEN "Cowa-bunga Test Client"
WHEN trip_client_id = "stY6CXv8mXmqF8hsVYeU" THEN "Digi Pharm"
WHEN trip_client_id = "8YvhRBWGtTABrl6bhkjW" THEN "Dis-Chem Pharmacies"
WHEN trip_client_id = "lnM4rxcp6uVTw8RhLTX9" THEN "EconoFoods"
WHEN trip_client_id = "0C6fjhjLU6rnuoQyREOb" THEN "Geewiz"
WHEN trip_client_id = "M4sdn7UTA9JkIPyzzS4P" THEN "JD Group"
WHEN trip_client_id = "VCm2MFBrnAaMLQaImiJf" THEN "Kauai"
WHEN trip_client_id = "yVRnsmD9Ajl1OQlkX6Sg" THEN "Kauai Sandbox"
WHEN trip_client_id = "Ju2Ae08OZ83osvuIYkrs" THEN "Kristen's Kickass Icecream"
WHEN trip_client_id = "KVo2gnuzWvPH4XQnJyN2" THEN "Loop Demo"
WHEN trip_client_id = "xOCqjHDuWvkXnZAPeDFQ" THEN "Loop Logistics Test Client"
WHEN trip_client_id = "n5DfgLRRxbvUejwtcRJH" THEN "Loop Test Client"
WHEN trip_client_id = "Rh8sfJLs6NxNejo0PH1h" THEN "Loop Trial Sandbox"
WHEN trip_client_id = "nO31bVSIrraBlWS15Thr" THEN "Nando's Qatar"
WHEN trip_client_id = "FQmUHvoz3hcl5Ae44aW3" THEN "Nando's Botswana"
WHEN trip_client_id = "Hw1dSXB6hEkoQ8HhYmNW" THEN "Nandoâ€™s Mauritius"
WHEN trip_client_id = "zVznneXPn3Zaj75n5Q3N" THEN "Nando's SA"
WHEN trip_client_id = "BUo9UTsiu29sMsID5CKC" THEN "Nando's SA Sandbox"
WHEN trip_client_id = "ARIrLnDJ0TXBHjmPU5mG" THEN "OneCart"
WHEN trip_client_id = "qiv6Z8eHY2AyC7Gazv3w" THEN "Parcel Ninja"
WHEN trip_client_id = "OsyIw6UxAr94pXTKGFaU" THEN "Pizza Pasta Please"
WHEN trip_client_id = "F50C6dDsBqiqw7S5SCFG" THEN "Quench"
WHEN trip_client_id = "CQoCdzOEQZHAOE4k0b70" THEN "Quench Sandbox"
WHEN trip_client_id = "gp316ncFwbEiv9UMuCYH" THEN "Ram"
WHEN trip_client_id = "xrSHiB7rklASZSYz3LNR" THEN "Servest"
WHEN trip_client_id = "Zl8DamSfvyNnKZYf3dhS" THEN "Somerset Timbers"
WHEN trip_client_id = "1HkTWdBdgsKdBDjjIAYs" THEN "Spar"
WHEN trip_client_id = "ZAvKuwk6zfbwsun8yZ3j" THEN "Test Client Prod"
WHEN trip_client_id = "3Hm28GaJRBBIZByiZ9SA" THEN "The Delivery Company"
WHEN trip_client_id = "JTutPYoTUX6QIr3RdPuD" THEN "The Local Choice"
WHEN trip_client_id = "eEETls5ygWMXJ7JItyTG" THEN "The Local Sandbox"
WHEN trip_client_id = "YriWOTYxdKOHT37RBg50" THEN "The Local Choice Waterstone & Heldervue Pharmacy"
WHEN trip_client_id = "P6jlGGG6U4snbhmvt7Ca" THEN "Woolworths"
WHEN trip_client_id = "TdyaJR64vgu6fIhp06SU" THEN "XLink"
WHEN trip_client_id = "N9iBwT9x2ATYlD4kxwBT" THEN "Nology"
WHEN trip_client_id = "TnxiIlI4yVUaLSRKtLWZ" THEN "Triangle truck"
WHEN trip_client_id = "k36eLgmA3VsmJ937TD1W" THEN "Olivers Craft Logistics"
WHEN trip_client_id = "K0i9ICblxGZfqOjM8kwU" THEN "Olivers Craft"
WHEN trip_client_id = "4XMzzfQ4vkR0ELflNAAk" THEN "Cube Logistics"
WHEN trip_client_id = "mYPoEBMCCuqJ0DIZ7yfM" THEN "Courier Guy Technicians"
WHEN trip_client_id = "Q0wtTcXxdE3lSjHRppkH" THEN "Imperial Fast n Fresh"
WHEN trip_client_id = "3PhF68sAYqajPyTwjlJi" THEN "Fastener Agencies"
WHEN trip_client_id = "REvnJlwcn1cqJwvmLXmu" THEN "Yebo Fresh"
WHEN trip_client_id = "k1RkaeTPoHqr8BWmgqE7" THEN "Burger & Brew"
WHEN trip_client_id = "VARTjMf1gBEiVxrGNEmf" THEN "AM Couriers"
WHEN trip_client_id = "B0l6eGBH0UB7wOhWzZ9J" THEN "WooliesDash"
WHEN trip_client_id = "KHNmuax4WjaafWvTLmTg" THEN "Platinum Fuel"
WHEN trip_client_id = "3Hm28GaJRBBIZByiZ9SA" THEN "The Delivery Co"
WHEN trip_client_id = "OsyIw6UxAr94pXTKGFaU" THEN "P3"
END AS Client_Name
 FROM `cb-prod-297913.cb_prod_analytics.cb_end_orders_in_trip`
--WHERE trip_client_id IN ('TnxiIlI4yVUaLSRKtLWZ')
--AND trip_id IN ('kz9BD8j7ApR2cfhvspl4','B9ZimbYRzX4bOfhjxGcI')
ORDER BY trip_id

'''
df_orders = pd.read_gbq(query_orders, project_id='cb-prod-297913', dialect='standard', credentials=credentials,progress_bar_type='tqdm_notebook')

Downloading:   0%|          | 0/757813 [00:00<?, ?rows/s]

In [158]:
df_orders.head()

,trip_id,trip_client_id,driver_name,order_id,order_no,branch_name,branch_address,branch_lat,branch_lon,customer_name,customer_lat,customer_lon,delivery_distance,created_at,Client_Name
0,000Jcnjd3OQ51AkzgiMq,zVznneXPn3Zaj75n5Q3N,Mpumelelo Nkandla,Zgk1fspMEYoS2cjY8RAo,1941,Florida,"Cnr 9th Ave & Goldman St, Shop 21, Goldman Cro...",-26.177178,27.922963,Moeniera,-26.199780,27.914460,2.652603,2021-08-22 12:50:48.311000+00:00,Nando's SA
1,000cBQqqV4mwvaLNYjwa,zVznneXPn3Zaj75n5Q3N,Kazzy Kazzla,iIdrAybjQkdhkjsOatEY,1558,Leaping Frog,Cnr Mulbarton Rd & William Nicol Dr Shop G053B...,-26.011157,28.011922,Tasneem,-26.024770,28.035533,2.803151,2021-11-05 08:43:31.328000+00:00,Nando's SA
2,000jeXoJylm00mEojWdv,F50C6dDsBqiqw7S5SCFG,Partmose Mataruse,gmhzHFchotuJyShjCr3p,1645518340326407,DC Cresta,"Shop BL04, Cresta Shopping Centre, 2118 Weltev...",-26.131227,27.976253,Chane Coetzee,-26.139654,27.973722,0.970462,2022-02-22 08:29:24.481000+00:00,Quench
3,000uy5nZapODPCyiXgLJ,zVznneXPn3Zaj75n5Q3N,Moris Matsimela,crstIUWTIUe0vLw5Ba66,8412,Polokwane,"60 Schoeman St, Polokwane Central, Polokwane, ...",-23.909055,29.453709,MATHAPELO,-23.919480,29.455310,1.170593,2021-10-07 09:31:33.415000+00:00,Nando's SA
4,001K9pj7Gjhnf2Fstk2I,zVznneXPn3Zaj75n5Q3N,Wesley,B4ZviRCbcSwLiGMBmiDy,9709,Benoni Lake,"Tom Jones St, Shop E18, Lakeside Mall, Benoni,...",-26.184923,28.315579,Thuli,-26.226700,28.324520,4.730256,2022-02-04 17:03:54.037000+00:00,Nando's SA

In [136]:
API_key = 'AIzaSyCkrolSwjpPGufcigton0eEL891nbAju-E'
client = googlemaps.Client(key=API_key)

In [159]:
def haversine(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance between two points 
    on the earth (specified in decimal degrees)
    """
    # convert decimal degrees to radians 
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])
    # haversine formula 
    dlon = lon2 - lon1 
    dlat = lat2 - lat1 
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a)) 
    # Radius of earth in kilometers is 6371
    km = 6371* c
    return km

df_orders['distance_optimized_km'] = df_orders.apply(lambda x:haversine(x['branch_lat'], x['branch_lon'], x['customer_lat'], x['customer_lon']), axis = 1)

In [161]:
df_orders['branch_lat'] = df_orders['branch_lat'].astype(str)
df_orders['branch_lon'] = df_orders['branch_lon'].astype(str)
df_orders['customer_lat'] = df_orders['customer_lat'].astype(str)
df_orders['customer_lon'] = df_orders['customer_lon'].astype(str)

df_orders['branch_geo'] = df_orders['branch_lat'] + ',' + df_orders['branch_lon']
df_orders['customer_geo'] = df_orders['customer_lat'] + ',' + df_orders['customer_lon']

In [152]:
def get_gmaps_distance(row):
    result = client.directions(str(row['branch_geo']), str(row['customer_geo']), mode='driving')
    distance = int(result[0]['legs'][0]['distance']['value']/ 1000)
    #duration = int(result[0]["legs"][0]["duration"]["value"]/60)
    return distance
    
df_orders["distance_normal_km"] = df_orders.apply(get_gmaps_distance, axis=1)

In [153]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   trip_id                5 non-null      object
 1   trip_client_id         5 non-null      object
 2   driver_name            5 non-null      object
 3   order_id               5 non-null      object
 4   order_no               5 non-null      object
 5   branch_name            5 non-null      object
 6   branch_address         5 non-null      object
 7   branch_lat             5 non-null      object
 8   branch_lon             5 non-null      object
 9   customer_name          5 non-null      object
 10  customer_lat           5 non-null      object
 11  customer_lon           5 non-null      object
 12  delivery_distance      5 non-null      float64
 13  created_at             5 non-null      datetime64[ns, UTC]
 14  Client_Name            5 non-null      object
 15  distance_optimized_km  5 non-null      float64
 16  branch_geo             5 non-null      object
 17  customer_geo           5 non-null      object
 18  distance_normal_km     5 non-null      int64
dtypes: datetime64[ns, UTC](1), float64(2), int64(1), object(15)
memory usage: 888.0+ bytes

In [155]:
df_orders['difference_km'] = df_orders['distance_normal_km'] - df_orders['distance_optimized_km']
df_orders['minutes_saved'] = (df_orders['difference_km']/100)*60
df_orders['fuel_saved_litres'] = (df_orders['difference_km'])/13
df_orders['fuel_cost_saved'] = (df_orders['fuel_saved_litres'])*27.45
df_orders.head()

,trip_id,trip_client_id,driver_name,order_id,order_no,branch_name,branch_address,branch_lat,branch_lon,customer_name,...,created_at,Client_Name,distance_optimized_km,branch_geo,customer_geo,distance_normal_km,difference_km,minutes_saved,fuel_saved_litres,fuel_cost_saved
0,B9ZimbYRzX4bOfhjxGcI,TnxiIlI4yVUaLSRKtLWZ,Victor.Mentis,szks1GBQYwIZ96IpORqs,Tim 5,Trianlge Truck Hire main hub,"10 Model Rd, Witfield, Boksburg, 1459, South A...",-26.1750081,28.2141246,Macsteel service,...,2022-10-31 07:48:44+00:00,Triangle truck,5.374890,"-26.1750081,28.2141246","-26.227304,28.1995426",7,1.625110,0.975066,0.125008,3.431483
1,B9ZimbYRzX4bOfhjxGcI,TnxiIlI4yVUaLSRKtLWZ,Victor.Mentis,1ZhS6vunMHvfp3B6kaus,Tim 3,Trianlge Truck Hire main hub,"10 Model Rd, Witfield, Boksburg, 1459, South A...",-26.1750081,28.2141246,Stewards & Lloyds Stormill,...,2022-10-31 07:44:22+00:00,Triangle truck,31.159905,"-26.1750081,28.2141246","-26.1987268,27.9346794",36,4.840095,2.904057,0.372315,10.220047
2,kz9BD8j7ApR2cfhvspl4,TnxiIlI4yVUaLSRKtLWZ,Victor.Mentis,WSp24UsmhRpxmJtkhVmE,Victor 2,Trianlge Truck Hire main hub,"10 Model Rd, Witfield, Boksburg, 1459, South A...",-26.1750081,28.2141246,Illovo sugar Flemming road Meadowdale,...,2022-10-27 06:20:47+00:00,Triangle truck,4.928117,"-26.1750081,28.2141246","-26.1517936,28.1748103",8,3.071883,1.843130,0.236299,6.486399
3,kz9BD8j7ApR2cfhvspl4,TnxiIlI4yVUaLSRKtLWZ,Victor.Mentis,rJOciXHqCz1PZyUIIVsE,Victor 1,Trianlge Truck Hire main hub,"10 Model Rd, Witfield, Boksburg, 1459, South A...",-26.1750081,28.2141246,Wavelength freight Quality Isando,...,2022-10-27 06:12:22+00:00,Triangle truck,2.499937,"-26.1750081,28.2141246","-26.1512394,28.2059546",4,1.500063,0.900038,0.115389,3.167441
4,kz9BD8j7ApR2cfhvspl4,TnxiIlI4yVUaLSRKtLWZ,Victor.Mentis,iwmbi47in8F1wZwJlLDs,Victor 3,Trianlge Truck Hire main hub,"10 Model Rd, Witfield, Boksburg, 1459, South A...",-26.1750081,28.2141246,Umbombo sugar Flemming road Meadodale,...,2022-10-27 06:26:47+00:00,Triangle truck,4.507941,"-26.1750081,28.2141246","-26.1487184,28.1808571",5,0.492059,0.295235,0.037851,1.039001

In [156]:
# Export to google sheets
file = 'C:/Users/leemn/Documents/Loop Service Account/cb-prod-297913-623cea238b9a.json'
sheet_id = '1zZKS7ZFe0Q5ycObY5Kc-jrIysUL9fCWCdH-Yce8b5bA'
sheet_name = 'distances'

def write_to_gsheet(service_file_path, spreadsheet_id, sheet_name, data_df):
    gc = pygsheets.authorize(service_file=service_file_path)
    sh = gc.open_by_key(spreadsheet_id)
    try:
        sh.add_worksheet(sheet_name)
    except:
        pass
    wks_write = sh.worksheet_by_title(sheet_name)
    wks_write.clear('A1',None,'*')
    wks_write.set_dataframe(data_df, (1,1), encoding='utf-8', fit=True)
    wks_write.frozen_rows = 1

write_to_gsheet(file, sheet_id, sheet_name, df_orders)